"""
Tool calling with LangChain (@tool + bind_tools) — the manual agent loop.

Learn:
  * @tool turns a typed Python function + docstring into a tool schema
  * ChatOllama.bind_tools(...) and AIMessage.tool_calls
  * executing tools and returning ToolMessage results
  * a retriever wrapped as a tool (agentic RAG); LangGraph automates this loop next
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
import init  # noqa: E402,F401

from langchain_core.tools import tool  # noqa: E402

from lib.utility.genai.factory import build_hr_vectorstore  # noqa: E402
from lib.utility.genai.frameworks.langchain import get_chat_model, run_tool_calling_loop  # noqa: E402
from lib.utility.genai.rag import format_context  # noqa: E402
from lib.utility.genai.reports import GenAIReport  # noqa: E402
from lib.utility.genai.retrieval import DenseRetriever  # noqa: E402
from lib.utility.genai.tools import safe_eval  # noqa: E402

_retriever = None


@tool
def calculator(expression: str) -> str:
    """Evaluate an arithmetic expression such as '48000 * 0.15 + 48000'."""
    return str(safe_eval(expression))


@tool
def search_hr_policy(query: str) -> str:
    """Search the company HR policy and return the most relevant passages."""
    return format_context(_retriever.retrieve(query, 2))


QUESTIONS = [
    "What is 12.5% of 64000, plus 2500?",
    "What does the HR policy say about freedom of association?",
]


def main():
    global _retriever
    store, _ = build_hr_vectorstore()
    _retriever = DenseRetriever(store)
    llm = get_chat_model(num_predict=200)
    tools = [calculator, search_hr_policy]

    report = GenAIReport("LangChain tool calling")
    report.full_table("Tool schemas generated by @tool", [
        {"name": t.name, "description": t.description, "args": str(t.args)} for t in tools])
    for question in QUESTIONS:
        print(f"Agent: {question}")
        answer, trace = run_tool_calling_loop(llm, tools, question, max_steps=4)
        report.grid([
            report.kv("Question / answer", {"question": question, "answer": answer}),
            report.table("Loop trace", trace),
        ])
    report.full_text("Key takeaways", "\n".join([
        "* bind_tools sends the JSON schemas with every request; the model replies with tool_calls.",
        "* The loop (call model -> run tools -> append ToolMessage -> repeat) is what every agent does.",
        "* LangGraph's ToolNode + tools_condition implement this loop as a graph (see 10_langgraph).",
    ]))
    report.save(__file__, "langchain_tool_calling_report.html")


if __name__ == "__main__":
    main()
